name: Mirroring to codecommit

on:
  push:
    branches:
      - main
      - Uat
  delete:

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up SSH
        shell: /usr/bin/bash -xe {0}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Push to codecommit
        env:
          INPUT_TARGET_REPO_URL: ssh://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test
        shell: /usr/bin/bash -xe {0}
        run: |
          export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -l ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}"
          git remote add mirror "$INPUT_TARGET_REPO_URL"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
